Create neonpunk theme to reviews.
gannerr/step pull request #19
Opened 2020-07-01 19:53 UTC by gannerr

Create neonpunk theme to reviews.

2020-07-01 19:54 UTC, gannerr commented
![Screenshot 2020-07-01 at 2 53 28 PM](https://user-images.githubusercontent.com/10457939/86285685-b1338700-bbaa-11ea-96ed-e28d19c01394.png)
![Screenshot 2020-07-01 at 2 53 18 PM](https://user-images.githubusercontent.com/10457939/86285688-b1cc1d80-bbaa-11ea-8eb2-b32751cd3642.png)

2020-07-01 20:27 UTC, terencedignon requested changes

2020-07-01 20:27 UTC, terencedignon commented on portfolio/src/main/webapp/css/reviews.css
> +  color: #00d7c3;
nit alphabetized

2020-07-01 20:27 UTC, terencedignon commented on portfolio/src/main/webapp/css/reviews.css
> +@keyframes flicker {
could you add a comment describing these definitions?

2020-07-01 20:27 UTC, terencedignon commented on portfolio/src/main/webapp/reviews.html
> +      <br><br><br>
Usually a code smell if you need more than one br or p. Could we use margin here instead?

2020-07-01 20:27 UTC, terencedignon commented
WOW this looks amazing. Had a few comments, but looking forward to seeing it in action.

2020-07-02 00:53 UTC, terencedignon approved these changes
Thanks., LGTM

2020-07-06 15:39 UTC, merged