Find optional meeting query
gannerr/step pull request #32
Opened 2020-07-16 14:56 UTC by gannerr

2020-07-18 02:31 UTC, auzlee requested changes
This looks much better! And thanks for the javadoc comments. I liked how you pulled the major components out into their own functions.

I had a few small nits/name suggestions, and then one more thought:
- Are we testing all the possible edge cases? It would be good to test more overlapping events, and sets where some events are "inside" other events.

2020-08-31 22:50 UTC, gannerr commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +  public List<Event> sortEvents(Collection<Event> events, MeetingRequest request) {
fair point

2020-08-31 22:51 UTC, gannerr commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +   * A comparator for sorting ranges by their start time in ascending order.
oops haha I will change to show it's a merge function

2020-08-31 22:51 UTC, gannerr commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +      MeetingRequest newRequest = new MeetingRequest(request.getOptionalAttendees(), request.getDuration());
:)

2020-08-31 22:52 UTC, gannerr commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +  //convert blocked times to available times
sure, I will make it private as there is no inherent need for it to be public

2020-08-31 22:53 UTC, gannerr commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +  public Collection<TimeRange> sectionTime(Collection<Event> events, MeetingRequest request, List<TimeRange> unavailableTimeRanges) {
I have renamed to findAvailableTimeRanges

2020-08-31 22:55 UTC, gannerr commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +  public void everyAttendeeIsConsideredOptionalAllDay() {
changed to just attendeeIsConsideredOptionalAllDay

2020-08-31 22:55 UTC, gannerr commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +  public void everyAttendeeIsConsideredOptional() {
changed to just attendeeIsConsideredOptional

2020-08-31 22:56 UTC, gannerr commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +  public void justEnoughRoomOptional() {
changed to justEnoughRoomWithOptionalAttendee

2020-08-31 22:56 UTC, gannerr commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +  public void noMandatoryAttendeesGaps() {
changed to noMandatoryAttendeesOptionalAttendeesWithGaps

2020-08-31 23:06 UTC, gannerr commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +      if (request.getAttendees().containsAll(event.getAttendees())) {
this is a great point. I will instead use !Collections.disjoint(request.getAttendees(), event.getAttendees()) to show if there exist ANY overlapping people.

2020-08-31 23:09 UTC, auzlee approved these changes

2020-08-31 23:09 UTC, merged